### ISSUE TITLE
Eth2 networking call 1

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-pm#111]
[Call 0](https://github.com/ethereum/eth2.0-pm/issues/106)

### Meeting Date/Time:
Meeting Date/Time: Wednesday 2019/12/18 at [13:00 GMT](https://savvytime.com/converter/gmt-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/dec-18-2019/1pm)

### Meeting Duration:
1.25 hours

### Agenda
1. Opening
2. Updates 
    * Whiteblock overview of gossipsub test results (pre-formal-writeup)
    * [Writeup on gossipsub sims from Harmony](https://hackmd.io/ZMBsjqdqSAK026iFFu_2JQ)
    * [Initial aggregation model work from proto](https://github.com/ethereum/eth2.0-pm/issues/111#issuecomment-567023169)
    * Status of Noise implementations/integrations
3. Spec items
    * `attnets` field added to ENR for phase 0
    * [content addressed messages for gossipsub](https://github.com/ethereum/eth2.0-specs/issues/1528)
        * ensure clients using native pubsub callback for validation
    * [handshake message](https://github.com/ethereum/eth2.0-specs/issues/1531)
    * [how often to send status](https://github.com/ethereum/eth2.0-specs/issues/1533)
3. Discussion of items that are under-{researched, tested, resourced} and plan of action
    * validator privacy
        * use of tor/[sphinx](https://github.com/Mikerah/specs/tree/master/sphinx)/onions
        * feasibility of obfuscation through multiple nodes, fake subnet subscriptions, etc
        * use of ZKPs as proof to join privileged subnet but without leaking val id
4. Open discussion
5. Closing remarks and plans for next call or other organizational items

**Comment by Mikerah** [comment]
On the topic of validator privacy, I started working on this [sphinx spec](https://github.com/Mikerah/specs/tree/master/sphinx) for use in libp2p. It's a current work in progress. The rational, though, is that modern network layer anonymity protocols use this packet format as their foundation. Moreover, it is implemented in many blockchain projects.

**Comment by AgeManning** [comment]
Discussion about moving to content addressed messages for gossipsub: https://github.com/ethereum/eth2.0-specs/issues/1528

**Comment by mcdee** [comment]
A handshake message with some base configuration/state information would be useful, described at https://github.com/ethereum/eth2.0-specs/issues/1531

**Comment by Nashatyrev** [comment]
Did a write up on Gossip simulation: https://hackmd.io/ZMBsjqdqSAK026iFFu_2JQ

**Comment by protolambda** [comment]
https://notes.ethereum.org/@protolambda/Hytd28rAH
^ Put this together as a start for writing the setup / strategy code for a gossip based attestation aggregation model, to see how far we could get with just gossip based aggregation. Going to implement it on top of the Harmony Kotlin simulation code

**Comment by arnetheduck** [comment]
> 9:21 AM] arnetheduck: we have one such change lined up: we currently require that block requests send at least one response_chunk - we'll likely be proposing that this requirement be dropped
> [9:24 AM] arnetheduck: consider a block range request: it might end up with no blocks because it's slot-based: currently if the request selects an empty range, there's no way to respond "correctly" - it can be resolved either by having no response_chunk or having a special "no data" error code, or potentially including a "null" marker in a "success" chunk. the first option seems the easiest and most consistent.

**Comment by benjaminion** [comment]
Quick meeting notes [here](https://hackmd.io/@benjaminion/SJ3W0qwAH)
