### ISSUE TITLE
BLS12-381 curve and aggregation libraries

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-pm#13]
I'm gathering info about the state of BLS12-381 implementations and associated signature/aggregation libraries. Please let me know any corrections or missing data.

## BLS12-381 Curve implementations
| Repo | Language  | License | Audit   | Notes  |
|----------------------|-----|-----------|------------------|----------|
| [ZCash pairing library in Rust](https://github.com/zkcrypto/pairing) | Rust  | MIT or Apache 2.0 (option) | Kudelsk  | Audit to be published "soon" |
| [Chia BLS12-381 in cpp](https://github.com/Chia-Network/bls-signatures)   | cpp   | Apache 2.0  | "when done" |      |
| [Chia BLS12-381 in python](https://github.com/Chia-Network/bls-signatures/tree/master/python-impl) | Python | Apache 2.0   | "when done" |        |
| [Chia python bindings](https://github.com/Chia-Network/bls-signatures/tree/master/python-bindings)   | python  | Apache 2.0  | "when done" | python bindings for cpp implementation |
| [Nim wrapper for Chia cpp](https://github.com/EmberCrypto/ec_bls) | Nim  | MIT | None  | wraps Chia cpp so those components are Apache 2.0 |
| [Herumi MCL](https://github.com/herumi/mcl) | cpp | [modified BSD](http://opensource.org/licenses/BSD-3-Clause) | not sure | | 
| [Milagro Crypto](https://github.com/apache/incubator-milagro-crypto)   |   C, cpp, Go, Java, JS, Python, Rust, Swift, WASM  |  Apache 2.0  | not sure  |  potential issues or unknowns with licensing |
| [py_ecc](https://github.com/ethereum/py_ecc)   |  Python  | MIT  | None  |       |

## BLS signature libraries
| Repo | Language  | License | Audit   | Notes  |
|--------|-----|-----------|------------------|----------|
| [Herumi BLS](https://github.com/herumi/bls) | cpp, go | [modified BSD](http://opensource.org/licenses/BSD-3-Clause) | | uses [Herumi MCL](https://github.com/herumi/mcl) |

NOTE: About to take off on a flight. I think the "BLS12-381 Curve implementations" is done to the best of my knowledge, but I haven't had a chance to add all of the "BLS signature libraries". Coming soon.

**Comment by ralexstokes** [comment]
https://github.com/dis2/bls12 -- Go impl that wraps the C RELIC lib.

https://github.com/dis2/blsig/blob/master/blsig.go -- example applications for signatures.

There is no license here and there is an open issue waiting for one...

**Comment by Mikerah** [comment]
Can you elaborate more on what the potential licensing issues for using milagro-crypto are? Most of the other projects are licensed under the Apache 2.0 license as well.

**Comment by djrtwo** [comment]
I think someone from nimbus was concerned that a portion of another library had been copied in without porting the license. 

Maybe @mratsim or @arnetheduck can speak to that

**Comment by mratsim** [comment]
You can add the [Nim wrapper for Milagro](https://github.com/status-im/nim-milagro-crypto) which is maintained by us, [Relic](https://github.com/relic-toolkit/relic) (only for the curve, not for the aggregation) and [Dfinity](https://github.com/dfinity/bn).

Relic BLS12-381 test vectors were used by Zcash and Relic the backend of Chia Network's library.

Regarding licensing, any library that rely on GMP will be considered derivative work of LGPLv3 or GPLv2 library.

Combining [GPLv2 + Apache v2 makes a library unredistributable](https://www.apache.org/licenses/GPL-compatibility.html) in binary form.

Chia has optional linking on GMP, Herumi's MCL has required linking on GMP, Relic seems to have [optional GMP dependency](https://github.com/relic-toolkit/relic/issues/71).

I've also noted the curve creators implementations in the [Athenaeum](https://github.com/status-im/athenaeum/blob/82b2830aba44ad0c70aadbf6556f82b747b16325/ethereum_research_records.json#L141-L157)

- https://github.com/leishman/bls_lib, implementation by a Stanford research advised by Dan Boneh (BLS = Boneh–Lynn–Shacham)
- https://github.com/blynn/pbc/blob/master/example/bls.c, implementation by Ben Lynn

**Comment by Mikerah** [comment]
I brought up the licensing issue in the milagro-crypto-js repository and the person who replied said that it doesn't make use of any GMP-licensed code. Here's the issue: https://github.com/milagro-crypto/milagro-crypto-js/issues/46

**Comment by mratsim** [comment]
Libraries using MCL will have this licensing issue. I didn't find any potential issue with Milagro, it's a project sponsored by the Apache Foundation.

**Comment by vbuterin** [comment]
Feel free to add https://github.com/ethereum/py_ecc, now with BLS-12-381 support.

**Comment by rauljordan** [comment]
MCL can build without GMP btw @mratsim - see more here: https://github.com/herumi/bls/issues/19

**Comment by paulmillr** [comment]
I have very simple and auditable JS / typescript implementation here: https://github.com/paulmillr/noble-bls12-381
