### ISSUE TITLE
API Call

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-pm#143]
As discussed on the previous eth2 call, we intended to do an API call this Wednesday to chat about [API formats](https://github.com/ethereum/eth2.0-APIs/issues/24), [beacon-node APIs](https://github.com/ethereum/eth2.0-APIs/issues/25), and [cross-format tooling and CI](https://github.com/ethereum/eth2.0-APIs/issues/26).

@protolambda and I are also putting together a comprehensive look at existing APIs as well as some notes on both general and more specific requirements. 

I propose we push this call to Monday to provide more time for input and discussion as well as digesting the additional resources we plan to publish tomorrow.

I also solicit more active engagement from at least one member of each client team.

## Agenda

* format [eth2.0-apis/issues/24](https://github.com/ethereum/eth2.0-APIs/issues/24)
    * OpenAPI / JSON -- general agreement (?)
        * int vs str-int
        * bytes (0x vs base64)
    * optional SSZ where easy/sensible
    * optional protobuf refs (?)
    * versioning
* api conversions/CI [eth2.0-apis/issues/26](https://github.com/ethereum/eth2.0-APIs/issues/26)
    * any updates
* bn apis [eth2.0-apis/issues/25](https://github.com/ethereum/eth2.0-APIs/issues/25)
    * HOW to make this RESTful while avoiding excessive verbosity
        * Identifiers in the context of our types (vs. query params)
            * `/beacon/{id}/resource` <- very nice construct, but would require some amount duck-typing
            * `/validator`, `/state_roots`, `/block_roots`, `/balances` all fit in nicely here
        * Define additional types (that don't map to basic SSZ types, e.g. `/forkchoice/ffg`, `/network/host` (or sub-components))
    * standardize useful computations and return types that clearly diverge from REST but are useful while not being burdensome on the eth2-client (e.g. `/beacon/forkchoice/individual_votes`)

Call Monday @ 2pm UTC

**Comment by djrtwo** [comment]
Tentative meeting time, Monday April 20th at 1:30pm UTC. Will confirm in ~2 days as these conversations progress

**Comment by alonmuroch** [comment]
Any specific topics you thought of? to maybe send some questions before hand?

**Comment by tzapu** [comment]
while not strictly API related, it would be useful to standardise the version string sent through the API. It would be most useful for 3rd party tools in the future
something like `Client/v0.0.0/githash/os/other/stuff` might be good... of course, the hash could be a part of semver as well...

**Comment by mratsim** [comment]
Quick notes: https://gist.github.com/mratsim/f0ab07dcb6e7c040bec5995b69391210

**Comment by protolambda** [comment]
Call notes: https://gist.github.com/protolambda/51152013648367e4d9bd1874d0860bc9
