### ISSUE TITLE
Funding for Ethereum 2.0 Call 37 Notes

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/eth2.0-pm#155]
**Meeting**: Ethereum 2.0 Call 37

A [transaction](https://etherscan.io/tx/0x5885f65bde7ef0e0266432c54b8de9018f1bf22c6c9282cbe3936238a3e19119) was initiated for this notes on May-02-2020 but it's status shows 'Dropped & Replaced'. cc: @ceresstation

**PR location**: https://github.com/ethereum/eth2.0-pm/pull/142

**Amount**: 100 SAI/DAI

**Wallet**: (ranjan.eth)
0xf13e477365B0FAa64130DA2FF663aAb20d32d929

Thanks.

**Comment by edsonayllon** [comment]
I think was the successful transaction: https://etherscan.io/tx/0x2f4c2f3a1ad2dc7707878b637c9a136f345b0f995895b1969917ddffec08276d 

[0xc92d76e01bd4e7ce25819c94fc6c3aea7b2cd155](https://etherscan.io/address/0xc92d76e01bd4e7ce25819c94fc6c3aea7b2cd155) is Scott's address.

**Comment by poojaranjan** [comment]
To clarify, two transactions were initiated on May 02, 2020.

1. Meeting 34: (Transaction ID) 0x2f4c2f3a1ad2dc7707878b637c9a136f345b0f995895b1969917ddffec08276d - Success
2. Meeting 37: (Transaction ID) 0x5885f65bde7ef0e0266432c54b8de9018f1bf22c6c9282cbe3936238a3e19119 - Dropped & Replaced

This issue is created for the second transaction.

**Comment by poojaranjan** [comment]
Payment received. 
The transaction id  0x9eb529db112e1060c70deb448245e5ed60205cecee86760b51780b1b0e320829.
