### ISSUE TITLE
Zinken landing page URLs

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-pm#183]
Collecting the URLs for the launchpad and blog posts.

| Client     | Zinken instruction URL* | Latest release URL** | Status |
|------------|------------------------|--------------------|--------|
| Lighthouse | (**updated**) https://lighthouse-book.sigmaprime.io/become-a-validator.html |                    | WIP  |
| Nimbus     | (same) https://status-im.github.io/nim-beacon-chain/install.html  |                    |      WIP |
| Prysm      | (**zinken-only**) https://docs.prylabs.network/docs/testnet/zinken  |                    | WIP |
| Teku       |  (same) https://docs.teku.pegasys.tech/en/latest/HowTo/Get-Started/Build-From-Source/  |                    | WIP |

***Zinken instruction URL**: the tutorial page URL that the launchpad will link to
****Latest release URL**: the page that client announces new software updates. e.g., GitHub release page, discord channel link.

**Comment by q9f** [comment]
`s/Zenkin/Zinken/g` :)

**Comment by cemozerr** [comment]
The teku and nimbus instruction URL's seem to be mixed up :D
