### ISSUE TITLE
Mainnet landing page URLs

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-pm#186]
| Client     | Mainnet instruction URL* | Latest release URL** | Status |
|------------|------------------------|--------------------|--------|
| Lighthouse | https://lighthouse-book.sigmaprime.io/ |                    |  |
| Nimbus     | https://status-im.github.io/nimbus-eth2/install.html  |                    |   |
| Prysm      |  https://docs.prylabs.network/docs/install/install-with-script  |                    |  |
| Teku       |  (same) https://docs.teku.pegasys.tech/en/latest/HowTo/Get-Started/Build-From-Source/  |                    | |

***Mainnet instruction URL**: the tutorial page URL that the launchpad will link to
****Latest release URL**: the page that client announces new software updates. e.g., GitHub release page, discord channel link.

**Comment by hwwhww** [comment]
Hey @rauljordan 👋
we need a link to Prysm's Mainnet instruction.

**Comment by mratsim** [comment]
https://status-im.github.io/nimbus-eth2/install.html

We change the repo name to prepare for mainnet and reduce Eth1/Eth2 confusion around branding.
There is a redirect though.

**Comment by hwwhww** [comment]
Lighthouse's link (https://lighthouse-book.sigmaprime.io/become-a-validator.html) is broken. I'm changing it to https://lighthouse-book.sigmaprime.io/ now.

/cc @paulhauner
