### ISSUE TITLE
Networking Call 6

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-pm#194]
[Call 5](https://github.com/ethereum/eth2.0-pm/issues/180)

### Meeting Date/Time:
Meeting Date/Time: Wednesday 2020/12/10 at [13:30 UTC](https://savvytime.com/converter/gmt-to-germany-berlin-united-kingdom-london-ny-new-york-city-ca-san-francisco-china-shanghai-japan-tokyo-australia-sydney/dec-10-2020/2pm)

### Meeting Duration:
1.25 hours

### Agenda
1. Opening
2. gossipsub v1.1 scoring
5. discv5.1 
6. block sync and WS state start
2. Updates 
4. Open discussion
5. Closing remarks and plans for next call or other organizational items

**Comment by sinkingsugar** [comment]
Regarding nimbus and nim-libp2p we have a few detailed points about gossipsub:

* Gossipsub
    * Scoring, need to sync parameters/tuning between clients
    * No penalty on IHAVE and PRUNE received traffic
        * Also graft, GRAFT messages for unknown topics are ignored, yet no penalty
        * Behavior score them?
    * No hard limit to the number of subscriptions a peer can send
        * In ETH2 case should be 69 max, if not a penalty should happen
        * In general subscriptions channel can be dangerous, no scoring happens
            * Add more behavior score?
    * P3 score can be extremely harsh on early prune
        * Not sure, probably it's intended and pruning is just wrong so early
    * Too harsh scoring can lead to self eclipsing
        * My node fails to keep LH nodes, probably happens to other clients too
    * IHAVE and in general control metadata traffic observations
* Multinet interop
    * Probably critical to tune gossipsub and avoid eclipsing of clients
