### ISSUE TITLE
Eth2 protocol upgrade naming theme brainstorming

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-pm#202]
# We need a code name!

The next Eth2 major upgrade (a.k.a hard fork) was tentatively named "*HF1*" in [the current spec](https://github.com/ethereum/eth2.0-specs/blob/0fd0db1ffc219e8686497874d975e18087f1bd40/specs/lightclient/beacon-chain.md#introduction). To effectively communicate and connect with the community, we should come up with a distinct name soon. ✨

Moreover, it would be cool to have **a unique naming theme** to link all future releases together!

The following comments are some candidates I've collected. If you have an awesome idea, please comment here! 🙌

Dear community members, please signal your opinions with positive emojis! ❤️ 👍 🚀  

## Hint: Some properties of a good theme/name
- Not too long (so it won't take too much space in a line)
- Not too short (need to be distinct!)
- Good for alphabetical order
- Culture-align with Ethereum community
- Legal (so we won't get sued)

**Comment by hwwhww** [comment]
## Candidate 1: [Chemical elements](https://en.wikipedia.org/wiki/Periodic_table)
### Examples
Hydrogen, Helium, Lithium, ...

### Proposer
Hsiao-Wei Wang (@hwwhww)

### Notes
- We may need to add an adjective if we want to make it in alphabetical order.
- Pros: Very neutral. Also, "Ether/Aether" is the name of one of the [classical element](https://en.wikipedia.org/wiki/Aether_(classical_element)).
- Cons: It may be tricky if Constantinople/St. Petersburg forks case happen.

**Comment by hwwhww** [comment]
## Candidate 2: [World of Warcraft Zones](https://wow.gamepedia.com/Zone)

### Examples
A: Azshara/Ashenvale/Arathi, B: Badlands/Blasted Lands, C: ?, D: Desolace, E: Elwynn Forest, F: Feralas/Felwood...etc.

### Proposer
Vitalik Buterin (@vbuterin)

### Notes
WoW!

**Comment by hwwhww** [comment]
## Candidate 3: Any collection of [mythical objects](https://en.wikipedia.org/wiki/List_of_mythological_objects)
### Examples
- Mythical astronomical objects/planets
- Mythical weapons (not friendly?)
- Mythical trees
- Mythical musical instruments

### Proposer
Diederik Loerakker (@protolambda)

**Comment by edsonayllon** [comment]
Ethereum 1 upgrades are named after cities.

I'd like to continue the theme of physical locations, but do so with a different kind of physical locations.

I'm thinking star names. 

![image](https://user-images.githubusercontent.com/34966228/107342023-57226a80-6a85-11eb-8a52-322b57d005fa.png)

**Comment by q9f** [comment]
## Candidate 5: [Solar Systems](https://evemaps.dotlan.net/region/Heimatar)
### Examples
Pator, Rens, Dal, ...

### Proposer
Afr Schoe (@q9f)

### Notes
* We can start with high-security systems and slowly work our way down.
* Pros: We should be sorted for at least [7000+](https://www.pcgamer.com/the-9-year-journey-to-explore-each-of-eve-onlines-7805-solar-systems/) upcoming upgrades.

**Comment by protolambda** [comment]
Retracting my naming suggestion. Mythical astronomical objects/planets may as well just be astronomical objects/planets/stars/solar systems. Let's just make sure we don't overlap with something like Cosmos though.

**Comment by lightclient** [comment]
## Candidate 6: [City Names](https://en.wikipedia.org/wiki/City)
### Examples
Amsterdam, Berkeley, Cario, ...

### Proposer
Matt Garnett (@lightclient)

### Notes
* There are many cities, it's unlikely we'll ever run out.
* We can layer additional meaning on top (e.g. devcon venues, like eth1).

**Comment by superphiz** [comment]
## Candidate 7: [Months of the Year](https://en.wikipedia.org/wiki/Month)

### Examples

January, February, March ...

### Proposer

[superphiz](https://twitter.com/superphiz)

### Notes

* The sentimentality is well known around the world
* The naming offers some context related to growth and development - January is "early" while March has a seasonal relationship with spring. As we progress toward the later months & forks the chain be mature and stable.
* Twelve instances are enough to last several years into network maturity.
* This could cause scheduling confusion if the "March hard fork" is scheduled for September.

**Comment by timjp87** [comment]
## Candidate 8: [Ordinal Numeral](https://en.wikipedia.org/wiki/Ordinal_numeral)
 ### Examples
 First, Second, Third ...
 
 ### Proposer
 [timjp87](https://github.com/timjp87)
 
 ### Notes
 * As sequential as it can get
 * Goes on forever
 * Simple
 * Neutral

**Comment by prestonvanloon** [comment]
# Candidate 9: [Semantic Versioning](https://semver.org/)

Examples:
- eth2.1
- eth2.2.5
- eth3.0

Proposer:
Preston Van Loon (@prestonvanloon)

Notes:
- Boring
- Not cool
- Easy to understand 
- Standardized 
- Not really a "code name". So maybe this idea can be used in conjunction with another idea.

**Comment by mauroaccornero** [comment]
# Candidate 10: [Space missions/programs](https://en.wikipedia.org/wiki/List_of_human_spaceflight_programs)
## Examples:
* Apollo
* Biomass
* Curiosity
## Proposer:
Mauro Accornero (@mauroaccornero)
## Notes:
* Represent the efforts and sacrifices of people working on an ambitious project.
* Not focused on a single country, [ESA](https://www.esa.int/ESA/Our_Missions) for example, have a good list like other countries.
* Allow custom characterization,  supported by a single mission/program purpose and history.
* Maybe can give good inspiration for more ideas.

**Comment by timjp87** [comment]
# Candidate 11: [Geological Time Scale](https://en.wikipedia.org/wiki/Geologic_time_scale)
## Examples:
* Eocen
* Oligocene
* Miocene
 
## Proposer:
timjp87(https://github.com/timjp87)
 
## Notes:
* Geological time has epochs...get it?...Epochs.
* Sequential
* Sciency

**Comment by ladidan** [comment]
### Candidate 12: [Instruments](https://en.wikipedia.org/wiki/List_of_musical_instruments)
**Examples**

- Zither, Double bass, Cowbell, Harmonica, Wood block, Laser harp, Trombone, Vuvuzela, ...

**Proposer**
ladidan

**Notes**

- every instrument adds a new flavour of tone to the magic of the ethereum symphony _(maybe a bit solemn, still like it though)_
- ensembles of instruments are self-sovereign cohorts
- music connects people / represents a universal language
- bar by bar -> block by block
- infinite composability

**Comment by mohsenghajar** [comment]
Candidate 13: Popular video games

In the order of release date of the first version of the game.

Examples:

1. Pong
2. Pac-Man
3. River Raid
4. Wolfenstein
5. Dune

- pros: a lot of gamers within the community
- goes from simple to more complex with more perks
- cons: won't be in alphabetical order

**Comment by mikeyme454** [comment]
I think hf1 naming convention could be cool relative to string theory.  Strethereum... ETH & SETH 😁..DUNNO ..the string theory  framework definition is inline with ETH's hard fork fixes and it's cool and simple 😎..  it's a good name ..

String theory::

In physics, string theory is a theoretical framework in which the point-like particles of particle physics are replaced by one-dimensional objects called strings. String theory describes how these strings propagate through space and interact with each other.

Fuck parachains

**Comment by derbaltasar** [comment]
Candidate 14: Human hormones especially [neurotransmitter](https://en.wikipedia.org/wiki/Neurotransmitter) families like [tryptamines](url), these family of molecules is such interessting thing, cause there will be science.... wait this is such a interessting thing, I don't know where to start...
ok I start with the lesser interessting things, and try to increase the Level of interesst for everybody similarly.

To the chemical familly of the tryptamines, you can count a lot of molecules. And some of them are known well, the most known tryptamine is seretonine, everyone should have heard of it, or maybe: melatonine, it is maybe not the only neurotrans handling diziness... but the most known and I think most known about. If it is dark the melatonin begins to be formed by enzymes and if you sitting on a couch your eyes will be hard to keep open...  if it's light, "the third eye" (german word for pineal gland) stops producing Melatonin and your ready for work or having very active sex or what ever.....
All these tryptamines are produce by a gland, called the pineal gland... There are only 2 glands in the brain which exists only one time, the pineal gland and the epitalamus. All other parts of the brain has two parts, right and left. The pineal gland produces also an other molecule which is much MORE fascinating. The name is Dimenthyltryptamine. Dr. Rick Strassman which was the first western scientist getting such a deep inside in a world which is beyond ours, not only this, this world seems to be build by every beeing inside it, if the beeings are aware about what they are.... consciousness and of course not in the everyday awareness. You can also reach this states of mind through meditation is better cause you can controll it and already grown spiritually that maybe you won't need the experiences anymore.. But if you wanna do it that way, and I will never negotiate the fact that reaching these states of consciousness by meditating.... BUT for this states you must do a long journey through a mostly thoughtless state of mind, which is very hard these days and why, I think I don't must tell you. Look 1 min in the TV if you have one, then you know what i mean, and then throw it out of the window...Believe me, you won't need it, it is only an addiction, and you don't have to be treated, maybe some people, those who already watch things like the jungle camp (german bull shit). Or no people watching such thing are still lost forever, you can only shoot em....

I hope i won't shock some people, cause please realize, halluzinogen drugs have no addictive potential.... the opposite is the case, for example in the USA the Indians are still allowed to do their rituals, which includes also the psychoactive peyote or San Pedro cacttus, both include mescalin.
The Shamans often try to get friends of friends to come cause they are addicted , mosty from optiates. The People with addiction often drink only a little bit, cause they got fear what the Meskalin will show them. I had always a sentence for me, no matter how deep i was in the rabbit hole, these words help for real! (normal I tell it in german -> "Du erlangst erst die Kontrolle wenn du aktzeptierst dass es keine gibt" in English "You only reach control in the moment you realize that there is no control"
This senctence I created in the time (about 20 month) in which i only took weed and LSD every weekend, If there had been no tollerance you build against substances, I would have take it everyday. Then this part of my life ended and a year later I tried the first and only time ayahuasca. A friend of mine, is from Brasilia and was writing with a peruish shaman . After 2 week of writing, he was sure that we dont do shit wtihit, and we really never had a thiought about that. I also hated the storrys when a guy was tripping and need help cause he/she is getting his/herself deeper in the pychological abyss...
I was a guy, helping everybody, who needed help. And I hated storrys about guys which didn't help but did the opposite!

So I must write not so much, I come know to the scientific things, cause Dr. Strassmann found out that our third eye produces the DMT in high dosis, when we are born as a little baby, and in the moment we die... and sometimes we dream special dreams in which DMT is also involved.
Strassman wrote a book, really goood, named DMT-Molecule of Consciousness. The Interessting thing is also that the experiences made by the probands are similar to near death experiences, if you would read 2 of them, after you can't say which
is the DMT experience and which is the neardeath xp....

From these experiences you can bring knowledge from these dimensions back in our allday life, it could be a thinking trick to get better talking with your mum, but also technical stuff, I think very much scientists couldn't invent their biggest inventions without the help of tryptamines (I forgotto tell that every indogene people from all over the world, found a healing plant which all contain a tryotamin.... Only today with science an chemistry we  can understand the similarity between the plants, and if the iindogen people, and that the plants must be anything special, why should medicinmen from around the world, without communication! Choose the plants for spiritual and physical healing.

Amazonas      -> Ayahuasca            -> MAO-Hemmer + 5-Meo-DMT + DMT
Mexico            -> Pilze                      -> Psilocybin/Psilocin
Afrika              -> Ibogain-Wurzel      -> Ibogain
SouthAmerika -> Aga-Kröte, uvm.     > Bufotenin

When I talked about the scientists, of course most of these cases won't get known, cause it's like being a pilot and telling your cheef that you saw 3 UFOs the last flight.... määääp unemployed!
Ok as a scientist, maybe it is not so hard, I know one, and you all know him indirect... the founder of the Polymerase Chain Reaction (PCR), which were the first tests for the fake virus which is used to make unethical Laws, and so much more, I would need again 1000 words....
Kary Mullis got the Nobelprice in 1993 for his invention in 1983. And only cause he is a man of truth, they already talk shit about him on wiki....

From the beginning he said, his method is not able for testing viruses, no good sentence from the inventor of PCR, put how lucky are the pharma companies... in his autobiography he wrotes "that without LSD he think he wouldn't have the nobelprice..."

Please realize, this is the guy who brought us DNA, the whole cop DNA evidence things and so won't work without his work. And the pharmasa have no better job to peach a good scientiest which also died 2 years ago... So no chance to defend himself.

https://en.wikipedia.org/wiki/Kary_Mullis
https://en.wikipedia.org/wiki/Tryptamine
https://en.wikipedia.org/wiki/Epithalamus


Ok I hope anybody understand my proposal, ---> I would like the name Tryptamine :)

**Comment by dmichulke** [comment]
Candidates 14-17:

Moons: Luna, Europa, Ganymede
Reasoning: 50+% of the user base aim for exactly this

Attacks on the chain: 51% attack, malleability issue, double spend
Reasoning: Robotraders might interpret this negatively and create a setback in price

Name of Cryptocurrencies in order of market cap ("The bitcoin hard fork of ethereum", ...)
Reasoning: Confuse everyone 
   
The old 4 elements: Earth Fire Water Wind
Reasoning: Ether is the fifth element

**Comment by ProkhorZ** [comment]
Tip: Monero creates distinctive names by using double names for hard forks. See the [naming convention](https://github.com/monero-project/meta/blob/master/NAMING.md) and the [releases](https://github.com/monero-project/monero/releases). Chemical elements are used in the order of the periodic table (with one exception), followed by a celestial object chosen shortly before the fork, with a preference for alliteration. Of course it would be appreciated if Ethereum used a different scheme. 

For more inspiration, I have a [collection of naming schemes](https://github.com/ProkhorZ/nerdy-naming-schemes) including links to other sources.

@superphiz @dmichulke Maybe you'd like the list of [Star Trek characters](https://github.com/ProkhorZ/nerdy-naming-schemes/blob/master/themes/StarTrek.txt), where Number One (from the pilot episode) is the third name.

**Comment by AroundTheBox** [comment]
**Candidate 18 - Mountains**

Using mountain names conveys the difficulty of getting to each release and the achievement when each is conquered.

Choosing names around the world shows the global nature of Ethereum, so starting with the seven peaks you’d have Aconcagua, Denali, Everest, Kilimanjaro, etc.

It’s of course also easy to create an aplphabetical list - Annapurna, Bogda, etc.

**Comment by henkevdb** [comment]
**Esperanto numbering maybe ?**
The word esperanto translates into English as "one who hopes" ;
https://en.wikipedia.org/wiki/Esperanto

https://www.languagesandnumbers.com/how-to-count-in-esperanto/en/epo/

**Comment by uberchar** [comment]
## **Candidate 21: Spaceships/Spacecrafts**
Both fiction and non-fiction
Examples: Hyperion, Millennium Falcon, Curiosity

Reason: Everyone is searching for moonshots may as well be the ship that takes you there. Beacon chain + shards are like a flagship + smaller ships

**Comment by AroundTheBox** [comment]
**Candidate 22: Fictional Materials**

Vitalik came up with the name for Ethereum looking at a list of fictional materials, so why not do the same for ETH 2.0 forks?

We can easily come up with an alphabetical list: Adamantium, Beskar, Computronium, etc.

https://en.m.wikipedia.org/wiki/List_of_fictional_elements,_materials,_isotopes_and_subatomic_particles

**Comment by AroundTheBox** [comment]
**Candidate 22: Fictional Materials**

Vitalik came up with the name for Ethereum looking at a list of fictional materials, so why not do the same for ETH 2.0 forks?

We can easily come up with an alphabetical list: Adamantium, Beskar, Computronium, etc.

https://en.m.wikipedia.org/wiki/List_of_fictional_elements,_materials,_isotopes_and_subatomic_particles

**Comment by hwwhww** [comment]
@hwwhww forwarding the proposals for a friend.

---

### Foreword
I assert the two largest criteria for an eth2 naming conventions are:
1. Topical / on-theme (science, utopian futurism, technology, exploration, etc.) Think something that conveys the spirit of the current ethereum.org design.
2. Memeability.  We want a theme for which it takes low effort for the community to generate memes.  Dogecoin is obviously the king here.  But another is Polkadot, where they represent their brand simply by an attractive person wearing polkadot clothing with various facial expressions.

Given these two constraints, I propose two possible themes:

## Candidate 23: Galaxy and Celestial Objects

### Proposer
Anonymous

### Examples
* Andromeda
* Blackhole / Black Eye Galaxy
* Comet / Cartwheel Galaxy
* Dark Matter
* [See](https://en.wikipedia.org/wiki/List_of_galaxies) [more](https://en.wikipedia.org/wiki/List_of_galaxy_groups_and_clusters) candidates...


There was a prior proposal that we use *stars* instead of galaxies and then use galaxies for eth3.  I respond that galaxies are more photogenic than individual stars, so why not just jump to that.  And for keeping galaxies for eth3, I presume the ethereum tastemakers will prefer deciding their own theme instead of one being dictated by the past.  Yay empowerment.

**Pros**
* Fits with the futurism/exploration theme
* Quite photogenic (hello [horse head nebula](https://en.wikipedia.org/wiki/Horsehead_Nebula)!)
* Overlaps with Cosmos, who these days is increasingly being a friend of Ethereum.  So this could be one more bridge.

**Cons**
* Less personality.  A little impersonal.
* Overlaps with Cosmos.

**Comment by hwwhww** [comment]
@hwwhww forwarding the proposals for a friend.

---

## Candidate 24: Names or objects from Sci-Fi media

### Proposer
Anonymous

### Examples
* Aeon Flux / Akira
* Bladerunner / Back to the Future
* [The Culture](https://en.wikipedia.org/wiki/The_Culture)
* Do Androids Dream of Electric Sheep? / [Daemon](https://en.wikipedia.org/wiki/Daemon_(novel_series)) / [Deus Ex](https://en.wikipedia.org/wiki/Deus_Ex) / Dune
* Ex Machina / Ender's Game
* [Fifth Element](https://en.wikipedia.org/wiki/The_Fifth_Element)
* Ghost in the Shell
* [More](https://en.wikipedia.org/wiki/List_of_cyberpunk_works) and [even more](https://en.wikipedia.org/wiki/List_of_films_set_in_the_future)...

**Pros**
* ***Extreme memeability***
* Wide variability in themes
* When a hardfork is named after something you haven't experienced, you now have reason to go explore it.

**Cons**
* Different people likely to have their favorite media that they want included
* By raw numbers, science fiction is usually more dystopic than utopic.  Not a lot of utopian science fiction to choose from, but we can probably just reframe from anything that is an explicit dystopia (e.g., [Brazil](https://en.wikipedia.org/wiki/Brazil_(1985_film))).
* Hidden meanings likely to be read into choices

**Comment by lfgarske** [comment]
Candidate 25: Characters in drama

**Examples**
Ariel, Beatrice, Cordelia, Demetrius...
(Characters of The Tempest, Much Ado About Nothing, King Lear, A Midsummer Night's Dream...)

**Proposer**
Lucas Garske (@U203D)

**Notes**
Since the development of a complex projects entails not also pleasure but also a lot of drama, characters in drama could work as a suitable theme for upcoming releases. 
Many plays are universal, regardless of time and space. Since there are a lot of plays to choose from, it is possible to find references to current development steps and by doing so "characterize" the corresponding step of development. Needless to say that the final step should probably a character from a comedy rather than a tragedy :)

**Pros:** Alphabetical order, lots of material, leeway to add meaning to a particular development step 
**Cons:** Characters not easily recognizable for most people.

**Comment by schajose** [comment]
People who changed the world in a positive way, in alphabetic or time order. What happens now is "changing the world". So lets continue history into future

Example: 
Mandela
Curie
Einstein
King
Da Vinci
Jesus
Theresa
Gandi
Orwell
Gallileo
...

**Comment by Souptacular** [comment]
## Candidate 27: Famous animals from movies and TV shows

### Proposer
Hudson Jameson

### Examples
* Airbud
* Babe (The Pig)
* Chance (Homeward Bound)
* Dug (from Up)
* Eeyore 
* Flit
* Gidget
* [More](https://en.wikipedia.org/wiki/List_of_animals_in_film_and_television) and [more](https://nerdist.com/article/ranking-the-best-disney-animal-companions/).

**Pros**
* Cute!
* Lots of names!
* Brings fond memories of your favorite animals from media!

**Cons**
* Finding an animal that starts with X.

**Comment by Souptacular** [comment]
## Candidate 28: The word "ethereum" but with an alphabetical letter in front of it and exclamation point at the end

### Proposer
Hudson Jameson

### Examples
* Aethereum!
* Bethereum!
* Cethereum!
* Dethereum!
* Eethereum!
* Fethereum!
* Gethereum!

**Pros**
* On brand!
* Well ordered!
* Alphabetical!

**Cons**
* Trolololol

**Comment by LamboshiNakaghini** [comment]
### Candidate 29: Simply express each hardfork as a phase of Eth2. 

**Proposer**

Lamboshi

**Examples**

Phase 0
Phase 1
Phase 2
Phase 3

This upcoming hardfork would be phase 0.

**Pros**

Simple
Clear
Concise

**Cons**

 Can't think of any. Happy to hear feedback.

**Comment by poapxyz** [comment]
**### Candidate 30: The word freedom in different languages**

**Proposer**

Patricio Worthalter 

Examples

Frihed (Danish)
Libertad (Spanish)
Freedom (English)
vapaus (Finnish) 
özgürlük (Turkish)
wolność (Polish)
ñembisy (Guarani)
Kalayaan (Tagalog)
Others: https://www.freelang.net/expressions/liberty.php

**Pros**

Mission driven
Lots of options
Easy to associate a flag a emoji with
Quite unique

**Cons**

Lots of similarity between lenguages for example German is Freiheit and Duth is Vrijheid.

**Comment by isaac-art** [comment]
### Candidate 31: Seasame Street Muppets

**Examples**
Abby Cadabby
Beautiful Day Monster
Count von Count
Don Music
[more](https://en.wikipedia.org/wiki/List_of_Sesame_Street_Muppets)

**Proposer**
Isaac Clarke 

**Notes**
Cons: Theres only about 100 or so.

**Comment by Phistr90** [comment]
> ## Candidate 27: Famous animals from movies and TV shows
> ### Proposer
> Hudson Jameson
> 
> ### Examples
> * Airbud
> * Babe (The Pig)
> * Chance (Homeward Bound)
> * Dug (from Up)
> * Eeyore
> * Flit

Come one. We all know that F would have to be Flipper.

**Comment by KevinVitale** [comment]
### Candidate 32: Year & Month ([Ubuntu Style](https://en.wikipedia.org/wiki/Ubuntu_version_history))

#### Examples
- 21.06
- 22.01
- 22.08
- 23.04
- ...

#### Proposer
@KevinVitale

#### Pros:
 - Unambiguous;
 - Informative;
 - Well organized;
 - Codename Optional
 
#### Cons:
 - Boring

**Comment by A2be** [comment]
> # Candidate 10: [Space missions/programs](https://en.wikipedia.org/wiki/List_of_human_spaceflight_programs)
> ## Examples:
> * Apollo
> * Biomass
> * Curiosity
> 
> ## Proposer:
> Mauro Accornero (@mauroaccornero)
> 
> ## Notes:
> * Represent the efforts and sacrifices of people working on an ambitious project.
> * Not focused on a single country, [ESA](https://www.esa.int/ESA/Our_Missions) for example, have a good list like other countries.
> * Allow custom characterization,  supported by a single mission/program purpose and history.
> * Maybe can give good inspiration for more ideas.

A large con on this is that nearly all space programs during the first six+ decades since humans came to possess the technology of spaceflight were a) **government agency space programs** and b) **done by the gvmts of the richest/most-powerful nation states**, totally missing much of the global population.  Neither comports with what Ethereum is all about, or the ethos of the Ethereum ecosphere.

The SpaceX/Elon Musk privately-funded programs to develop reusable rocket technology, and to build a Mars transportation infrastructure system are exceptions.  However both are too new; and the Mars program is only in its infancy with an uncertain future.

**Comment by Buttaa** [comment]
Candidate 32: Emojis

Proposer
Butta


Examples
:heart: fork ❤️ 
:new_moon: fork 🌑 
:fork_and_knife: fork 🍴 


Pros: 
emojis are easy to memorise 
covers many categories (fruits, cars, flags..)

Cons: 
¯\_(ツ)_/¯

**Comment by superphiz** [comment]
With the naming of the first hard fork being the most critical component of release, I propose that all work on other issues should halt until a name has been chosen.

**Comment by A2be** [comment]
## Candidate 32: Name after various [stellar nurseries](https://en.wikipedia.org/w/index.php?title=Stellar_nursery) of the astrophysical space-time that surrounds us.  Ethereum emerges new protocols and projects, just like stellar nurseries do.
### Proposer
A2be
 
### Examples
* [Aigle](https://fr.wikipedia.org/wiki/M16_(amas_ouvert)) (French spelling), is [Eagle](https://en.wikipedia.org/wiki/Eagle_Nebula) in English
* [Boomerang](https://en.wikipedia.org/wiki/Boomerang_Nebula) 
* [Cotton Candy](https://en.wikipedia.org/wiki/Cotton_Candy_Nebula)
* [Dragonfish](https://en.wikipedia.org/wiki/Dragonfish_Nebula)
* [Egg](https://en.wikipedia.org/wiki/Egg_Nebula)
* [Frosty Leo](https://en.wikipedia.org/wiki/Frosty_Leo_Nebula)
* [Gomez's Hamburger](https://en.wikipedia.org/wiki/Gomez%27s_Hamburger)

### Pros
* growing many new projects and protocols, just like Ethereum
* future/tech orientation
* astrophysics themes have been popular here (stars, galaxies, SciFi fiction, etc.)
* would be easy to rotate in a diverse set of global languages that all use the latin alphabet; e.g., Aigle
* alphabetical

### Cons
* outside of most people's understanding (just like arcane subway stops in Eth1)

**Comment by Phistr90** [comment]
### Candidate 35: Name after (oldest) lighthouses 

**Examples**
For oldest (according to  https://www.oldest.org/structures/lighthouse/):

- Pharos of Alexandria (Short version  Alexandria) 
- Tower of Hercules (Short version Herkules)
- Lighthouse of Genoa (Short version Genoa)
- Hook Lighthouse (Short version Hook)
- Kõpu Lighthouse (Short version Kõpu)

**Proposer**
@Phistr90 aka phil.eth

**Pros**
- Keep the beaconchain theme
- Many available

**Cons**
- Hard to understand the naming convention without knowing the background

**Comment by Phistr90** [comment]
### Candidate 36: Name after tallest lighthouses 

**Examples**
For tallest lighthouses (according to  https://en.wikipedia.org/wiki/List_of_tallest_lighthouses):

- Jeddah Light
- Yokohama Marine Tower
- Palacio Barolo
- Statue of Liberty


Jeddah Light
--




Jeddah Light
--




Jeddah Light
--




Jeddah Light
--




**Proposer**
@Phistr90 aka phil.eth

**Pros**
- Keep the beaconchain theme
- Many available

**Cons**
- Hard to understand the naming convention without knowing the background

**Comment by vbuterin** [comment]
### Candidate 37: names of countries in mismatched languages

Proposer: @vbuterin

Examples:

1. Angleterre
2. Frankreich
3. Niemcy
4. Lengyelország
5. Mađarska

(in this order to preserve chaining)

#### Pros

* Confusing
* Potential for thousands of names

#### Cons

* Not all languages use the English alphabet so we would need transliterations eventually

### Candidate 38: characters and places in Studio Ghibli movies

Proposer: @vbuterin

Examples:

* Laputa
* Nausicaa
* Chihiro
* Totoro

#### Pros

* Castle in the Sky understood the value of Ethereum (or "Aetherium") three decades before everyone else: https://ghibli.fandom.com/wiki/Crystal_necklace

#### Cons

* Possibly a limited number of meaningful names

**Comment by hwwhww** [comment]
# [Announcement] The deadline of proposals and primary signals: 2021-02-22 @ UTC 02:22

**Comment by CarlBeek** [comment]
# Candidate 39: Powers of G1
## Examples:

```
0x97f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb
0xa572cbea904d67468808c8eb50a9450c9721db309128012543902d0ac358a62ae28f75bb8f1c7c42c39a8c5529bf0f4e
0x89ece308f9d1f0131765212deca99697b112d61f9be9a5f1f3780a51335b3ff981747a0b2ca2179b96d2c0c9024e5224
```

## Proposer:

@CarlBeek

## Notes:

### Pros:

* Eventually we'll discover everyone's private keys
* We won't run out of names nearly as soon as the other proposals
* Consecutive nature is intuitive

### Cons:

* None?

**Comment by LogicBeach** [comment]
**Candidate 40: Jupiter's Moons**

**Examples:**
1. Europa
2. Ganymeade
3. Io
4. Callisto
5. etc....

**Proposer: @Logic_Beach** 


**Notes:** 
I really like the massive expanse of astronomical names there are to choose from.
Also, seeing as ETH is 'mooning' let's go with moons!!!

**Pros:**

- Astronomy is cool!
- Cool photos for every moon
-Very distinct names.
-No shortage of names (Jupiter has 79 moons!)


**Cons:**

    None?

**Comment by greg7mdp** [comment]
# Candidate 41: Names related with light

> Interestingly `beacon` in `Beacon Chain` means a signal light

The next fork which adds support for light clients could simply be codenamed `Light`

There are many light related scientific terms that would make nice codenames. 

* For example the fork splitting the chain into multiple shards could be named `prism`.
* The fork that finally deprecates the POW chain and finalizes the transfer to POS could be called `Event Horizon` (there is no going back)
* the fork making ETH resistant to quantum algorithms would be called `quantum` (or `quanta`)

Scientific names or light related things
* photon
* gamma
* ultraviolet
* radiance
* spectral
* firefly

There are many light related proper names with varied meanings which can be used:
* Apollo: From Greek mythology, Apollo was the god of light, music and poetry.
* Abner: A Hebrew name meaning “father of light”
* Kiran: A Hindi name, this means “beam of light”
* Lucy: Meaning “light,” this name has Latin origins
* Thea: She was the Greek goddess of light

and there are many others, see [here](https://www.behindthename.com/names/meaning/light) for examples.

proposer: me :-)

**Comment by Dessix** [comment]
# Candidate [42](https://en.wikipedia.org/wiki/42_(number)): [Fermions](https://en.wikipedia.org/wiki/Fermion) and [Bosons](https://en.wikipedia.org/wiki/Boson) of the Standard Model
Multiple orders are available, from increasing energy to positioning in the standard model and date of confirmation.

## Examples currently discovered:
- Quarks (up, charm, top, down, strange, bottom)
- Leptons (electron, muon, tauon, electron-neutrino, muon-neutrino, tauon-neutrino)
- Gauge Bosons (gluon, photon, Z, W)
- Scalar Bosons (Higgs)
- Tensor Bosons (Graviton)

## Pros
- Sounds cool (Ethereum Muon, etc)
- Continuously evolving, discovering new potential version names which will be hype-words at the time of discovery
- Legally safe

## Cons
- Ordering is almost strictly non-obvious and arbitrary
- Neutrino subtypes are somewhat repetitive, but the V<sub>e</sub>, V<sub>μ</sub> and V<sub>𝜏</sub> notations can help here.

**Comment by hadv** [comment]
> * the fork making ETH resistant to quantum algorithms: `quantum` (or `quanta`)

@greg7mdp do you have detail document about this?

**Comment by greg7mdp** [comment]
> > * the fork making ETH resistant to quantum algorithms: `quantum` (or `quanta`)

> @greg7mdp do you have detail document about this?

I just made up forks that sounded possible (to me), I don't believe there is any plan for this one in particular.
