### ISSUE TITLE
Result for issue #202: Eth2 protocol upgrade naming theme brainstorming?

### ISSUE THREAD

**Issue by greg7mdp** [ethereum/eth2.0-pm#215]
So did Candidate 4 win? It would be nice to have some info on the reasons for this choice.

**Comment by tzapu** [comment]
at a quick glance it seems to be the one with the most reactions

**Comment by hwwhww** [comment]
Sorry for the late response!
The star names theme was (i) with the most reactions, (ii) rough consensus with Eth2 core devs, and (iii) community signaled in https://poap.vote/results/44
