### ISSUE TITLE
Eth2 Call 69

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-pm#229]
# Eth2 Call 69 Agenda

[prev: call 68](https://github.com/ethereum/eth2.0-pm/issues/226)

Meeting Date/Time: Thursday 2021/07/29 at 14:00 GMT
Meeting Duration 1.5 hours

*Danny is absent this week, @ralexstokes and @protolambda host*

1. altair-devnet-2
2. Client Updates
3. Altair
    - release and testing
    - planning
4. Research updates
5. Merge updates
6. Spec discussion
7. Open Discussion/Closing Remarks

**Comment by OisinKyne** [comment]
Will there be a streaming link for this call? Or a discord stage?

**Comment by protolambda** [comment]
@OisinKyne The call is being recorded, and will be uploaded to the youtube channel later. There may be some delay, we have a different call host this time.

**Comment by robram9572** [comment]
when does the call begin?

**Comment by robram9572** [comment]
Thanks, how to claim the poap for this call?

**Comment by robram9572** [comment]
Can you kinly send a poap link to me?

**Comment by Likong1** [comment]
Can you kinly send a poap link to me?

**Comment by benjaminion** [comment]
Quick call notes: https://hackmd.io/@benjaminion/SyZgz4l1Y

Apologies that thet are sparse towards the end; I had some computer issues.

**Comment by onmoo** [comment]
I like this poap ,can you give me one ?thanks

**Comment by lanse126326** [comment]
can u give me a poap，thank you

**Comment by superphiz** [comment]
Please DO NOT use this platform to request (or even discuss) POAP. POAPs are given to users during live events and will never be provided to people who ask. Abusing this platform steals valuable time from people who are working hard to develop on Etherem.

**Comment by onmoo** [comment]
You are right
You guys develop well to minimize GAS

**Comment by Likong1** [comment]
ETH2.0 is the future of blockchain.

**Comment by likong2** [comment]
When will ETH2.0 really start?
