### ISSUE TITLE
Production Readiness

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-pm#53]
Just want to begin a list and conversation of the things we need to be ready to move to production

* Long standing public testnet (how long?)
* Incentivized testnets
* Extensive Fuzzing
* Extensive static test vectors
* FV Deposit Contract
* FV BeaconChain safety+liveness
* Network stress testing to meet requirements with 300k+ validators split amongst `N` nodes (N == 10k?)
* 3 (absolute minimum of 2) clients "production ready"
  * External audits and security reviews
    * dos vectors
    * incentive analysis
  * Performed exceptionally in testnets

**Comment by atoulme** [comment]
* Documentation to start a validator or a beacon node
* Documentation for recovery
* Keystore standard
* Backup and restore procedures
* Metrics
* Logging to console and file

"Performed exceptionally in testnets" needs to be quantified.

**Comment by djrtwo** [comment]
From @JustinDrake 

> I'd say is capable of running without hickups (certainly, no consensus failures) in an adversarial cross-client testnet for at least 32 days. Has undergone thorough fuzzing and a security audit.

**Comment by atoulme** [comment]
What is "adversarial"? Can we list the behaviors this term covers?

**Comment by Mikerah** [comment]
I would add bounty hunting for others to come and attack the testnets and the economics surrounding the beacon chain.

**Comment by AgeManning** [comment]
A more immediate issue is to get everyone to come to consensus on the networking specification for production. 
Although we probably don't know what that is without extensive tests, we can agree on a starting point and iterate when/if we run into issues at scale.

**Comment by jannikluhn** [comment]
Maybe:

- network monitoring tool(s)/website(s): Similar to https://ethstats.net/
- failure analysis: What things may possibly go wrong (client bug, protocol bug, network failure, ...), what are the possible results (fork, network split, wrongly slashed validator, ...), and what options do we have to deal with them (ignore, fork, pitchforks, ...)

**Comment by JustinDrake** [comment]
> Long standing public testnet (how long?)

Requiring a multi-client (ideally 3 clients) public testnet be stable for 3 months without reboots or downtime feels about right to me :) My hope is that such a stable multi-client testnet will be deployed in Q1. With a 3-month stability requirement we'd be looking at Q2 launch at the earliest.

**Comment by mcdee** [comment]
Surely prior to the testnet there needs to be a lockdown of the phase 0 spec (bugs notwithstanding).  Is there a list of outstanding changes required before this happens?

**Comment by JustinDrake** [comment]
> Surely prior to the testnet there needs to be a lockdown of the phase 0 spec

Having a stable spec for the purposes of long-standing testnets was largely what was meant by "spec freeze". As I understand @djrtwo wants to make another release soon, also specifically designed for long-standing testnets.

**Comment by mcdee** [comment]
If I remember correctly the "freeze" was 0.8.0 but that's significantly different from 0.9.2.  There needs to be a 1.0.0 release so the spec stops being a moving target, and before that the idea of what additional changes may be introduced so that client teams know where to focus their efforts.

This doesn't require all of the specs to hit 1.0.0 at the same time.  The beacon chain spec, for example, could hit 1.0.0 separate to the networking spec.  But until the functional spec is nailed down there seems little point in attempting to start a long-running testnet, as restarts will be required with spec changes.

**Comment by djrtwo** [comment]
closing, we're in production
