### ISSUE TITLE
mocked start of eth2 for interop testing

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-pm#60]
# mocked start of eth2 for interop testing

As we push forward toward interop testing, we need to conform on a standard to mock testnet starts across clients _without_ an eth1 network from which to read deposits.

A network start consists of the following:

1. Genesis `BeaconState`
2. Network configuration
3. Agreed upon distribution of validators across nodes

### Generate deposits

The genesis `BeaconState` is created from two parameters `genesis_time` and `validator_count` that can be specified either in a YAML file or as command-line params. This method is appealing because it is both simple and succinct. The main drawback of this method is that all validators are initialized with `MAX_EFFECTIVE_BALANCE` to start

A list of `validator_count` `deposits` is derived using the first `validator_count` pubkey/privkey pairs from a shared pubkey/privkey rainbow table of valid pubkey/privkeys generated in the method below. `withdrawal_credentials` for each are set to `BLS_WITHDRAWAL_PREFIX + hash(deposit.data.pubkey)[1:]`. `amount` for each is set to `MAX_EFFECTIVE_BALANCE`. 

### Create genesis state

Clients must create the genesis state by calling `initialize_beacon_state_from_eth1()` with coordinated junk values for `eth1_block_hash = b'\x42'*32` and `eth1_timestamp = 2**40`, and with the list of `deposits` created in the prior section. The returned `BeaconState` must then be modified with `state.genesis_time = specified_genesis_time`.

Clients must _not_ run `is_valid_genesis_state` as this state is already considered valid. Specifically, we do not check nor care about `MIN_GENESIS_TIME` in these coordinated starts.

## Network configuration

The specs repo already contains two configuration presets -- `mainnet` and `minimal`. `minimal` will likely serve as a good choice for many interop tests. If there are components of this configuration that do not serve a specific need, we can add more configurations here.

## Distribution of validators across nodes

Simple: Do an even split between the various client teams participating and the initial validator indices. Client teams will then provision their nodes with some distribution of validators that they control. The rainbow table for pubkeys/privkeys should enable any distribution desired in a given test.

Another option is to add more coordination params to a YAML file `validator_map` that maps `pubkey`s to `node_id`s (`{pubkey: node_id`) where each client team runs a set of `node_id`s.

Seeking feedback on how we might bettercoordinate nodes, pubkeys, etc. Keeping it super simple to start.

## Pubkey/privkey generation

The following script is used to generated pubkey/privkeys for the first `N` validators. The `i`-th deposit/validator index uses the `validator_index_to_pubkey[i]` pubkey and associated privkey.

*Note, this deterministic privkey algorithm is not secure (due to severe modulo bias) and should only be used for testing purposes.*

```python
CURVE_ORDER = 52435875175126190479447740508185965837690552500527637822603658699938581184513
validator_index_to_pubkey = {}
pubkey_to_privkey = {}
privkey_to_pubkey = {}
for index in range(N):
    privkey = int.from_bytes(
        sha256(int_to_bytes(n=index, length=32)),
        byteorder='little'
    ) % CURVE_ORDER
    pubkey = bls.privtopubkey(privkey)
    pubkey_to_privkey[pubkey] = privkey
    privkey_to_pubkey[privkey] = pubkey
    validator_index_to_pubkey[index] = pubkey
```

**Comment by paulhauner** [comment]
This seems sensible to me.

Regarding _"Distribution of validators across nodes"_, we could add an `attached_validators` list of indices alongside `genesis_time` and `validator_count`. This becomes awkward with hundreds of validators but it meets interop requirements. A more scalable but less flexible alternative is passing `(first_validator_index, count_validator_indices)` (e.g., `A` has validators 0..999 and `B` has 1000..1999).

**Comment by djrtwo** [comment]
code for generating initial `N` privkey/pubkey pairs for the rainbow table

```python
validator_index_to_pubkey = {}
pubkey_to_privkey = {}
privkey_to_pubkey = {}
for index in range(N):
    privkey = sha256(int_to_bytes(n=index, length=32))
    pubkey = bls.privtopubkey(privkey)
    pubkey_to_privkey[pubkey] = privkey
    privkey_to_pubkey[privkey] = pubkey
    validator_index_to_pubkey[index] = pubkey
```

**Comment by CarlBeek** [comment]
All of the above seems very sane to me.

Is it worth defining how the clients split up the validators in the network start YAML file? Clients could just add `A` or `B` etc as a CLI argument when specifying the `yaml` flie.

Why bother using the hash of the `index` as the `privkey`? The `index` alone should just suffice, right? I worry about strange behaviors from some BLS lib because the output space of SHA256 is greater than the curve order. In addition, I think the `privkey` needs to be cast to an `int` as a bls privkey is just an integer (mod the curve order).

**Comment by djrtwo** [comment]
My understanding is that due to the curve order, 32-bytes is the max privkey (output size of sha256).

There are issues with aggregation when privkeys have certain relationships with eachother (can't remember the details here). Using a hash here from my understanding is safer.

------------

I'm down to standardize on how clients split validators at network start. What do you mean `A` or `B` as CLI argument?

**Comment by CarlBeek** [comment]
The curve order is 255 bits and only covers 45.28% of the sha256 output space (by my calcs). Depending on how it's implemented, `privtopub(x)` may require `x` to be less than the curve order to prevent modulo bias (`py_ecc` does not assert this, but other BLS libs may). That said, the bais favours the first 21% of the curve which is still a very large key space for testing. Rejection sampling is the correct way of doing this, but requires ~2 samples on average to get a legitimate key.

```python
def get_privkey(index: int) -> int:
    privkey = index
    while True:
        privkey = int.from_bytes(sha256(privkey.to_bytes(length=32, byteorder='little')), byteorder='little')
        if privkey < curve_order:
            return privkey
```

___

I agree there are strange relationships here with aggregated signatures equalling that of other validators. Probably good to avoid. Additionally, it's good to use the larger multiples of the generator too for BLS testing reasons.

___

The YAML file specifies client `A` gets validators [0, 1024) and `B` gets [1024, 2048) and then at runtime, each client specifies `--client A` and `--client B` respectively as CLI arguments.

**Comment by djrtwo** [comment]
Modified the key generation script based on feedback and discussion from @CarlBeek

**Comment by paulhauner** [comment]
I wasn't able to find a definition of `bls.privtopubkey(privkey)`, could you point me to it please? I'm interested in the padding of the secret key (if any).

Our library (Milagro Rust) is strict about only accepting 48 bytes as a secret key. It might be worth padding out those 31 bytes to be 48 to be maximally compatible. _Note: I recall that previously BLS was still big-endian, if that's still the case we need to pad accordingly._

@CarlBeek, what are your thoughts on endianness? :)

**Comment by ralexstokes** [comment]
@paulhauner p sure they are referring to this: https://github.com/ethereum/py_ecc/blob/master/py_ecc/bls/api.py#L49

it seems like we sidestep the issue in `py_ecc` by already just having an `int`. not sure why milagro requires an input of 48 bytes...

**Comment by CarlBeek** [comment]
Yup! Under the hood, it is ultimately an `int` in whatever language because that is, by definition, what an privkey is. Regarding endianness, I was using little for coherence with the rest of the spec, I don't see why it should be any different here.

**Comment by terencechain** [comment]
This seems like a reasonable approach to me, I encourage individual client team to try out this approach before meeting for interop. On our end, we have built an eth1 rpc server to mock deposit events for bootstrapping genesis: https://github.com/prysmaticlabs/eth1-mock-rpc/blob/master/README.md

It's working well, and it's nice to not have to wait for contract deployment and transaction to test run time

**Comment by arnetheduck** [comment]
For genesis, we're currently using a genesis file that contains a snapshot of the beacon state, and a second file containing various network parameters (boot nodes etc). In practical and detail terms, it's a simple json file with all the fields of the beacon state serialized (this can of course be yaml or whatever instead):

```json
{
  "genesis_time": 1563776102,
  "slot": 0,
  "fork": {
    "previous_version": [
      0,
      0,
      0,
      0
    ],
    "current_version": [
      0,
      0,
      0,
      0
    ],
    "epoch": 0
  },
  "latest_block_header": {
    "slot": 0,
    "parent_root": "0000000000000000000000000000000000000000000000000000000000000000",
    "state_root": "0000000000000000000000000000000000000000000000000000000000000000",
    "body_root": "AC39C79050670FC818B3733175F5A0E50A3CAD8C0484590456C7BCA1702CE185",
    "signature": "c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
  },
  "block_roots": [
    "0000000000000000000000000000000000000000000000000000000000000000",
    "0000000000000000000000000000000000000000000000000000000000000000",
...
```

One reason for doing it this way is because this can form the basis for weak subjectivity recovery - one way to look at weak subjectivity is that after N months, we socially agree on a particular beacon state to be the "new genesis" so to speak - thus it makes sense to be able to pass that in to the client. One can imagine that spreading the hash of this state (or the associated block) could be the way to distribute this agreement.

At the same time, also offers a convenient way of starting a client from a particular state instead of slot 0.

A procedural approach where events are mocked would be harder - deposits from the beginning of time would have to be replayed - it is generally also easier to build good tooling around declarative solutions as the tools can be made to understand the data much more easily.

**Comment by arnetheduck** [comment]
> There are issues with aggregation when privkeys have certain relationships with eachother (can't remember the details here). Using a hash here from my understanding is safer.

> I agree there are strange relationships 

can we quantify "safer" / "strange"? what are chances of randomly hitting two incompatible keys in the wild?

**Comment by djrtwo** [comment]
> For genesis, we're currently using a genesis file that contains a snapshot of the beacon state

I think this is certainly a desirable feature and one that we should conform upon, but the swiftness and ease of specifying a `[genesis_time, num_validators]` for rapidly iterating on small/short-lived testnets is highly desirable. Say we run a short testnet of 10 validators and then want to run one of 20, this would simply be changing a single value in the configuration/cli rather than rebuilding some state file and sharing it among clients. The end result is the same. Clients could (should) even use the script to build such a file to be fed into the system

> a second file containing various network parameters (boot nodes etc). 

Agreed on standardizing this.

> can we quantify "safer" / "strange"? what are chances of randomly hitting two incompatible keys in the wild?

I believe there can be uniqueness problems in aggregate signatures when there are trivial linear relationships between the keys. This wouldn't really be much of an issue in most cases other than the obvious reduction in security and the (unlikely) duplication of a signature for two different things.

**Comment by paulhauner** [comment]
@CarlBeek we have a basic implementation of your keygen function [here](https://github.com/sigp/lighthouse/blob/master/eth2/utils/eth2_interop_keypairs/src/lib.rs).

It'd be cool to have some test vectors to test against. Carl do you have an working implementation lying around anywhere?

**Comment by ajsutton** [comment]
Agreed, test vectors would avoid wasting time debugging these implementations at the interop event. I'd say a few of the validator private keys, a couple of the resulting deposit data and the final `BeaconState` for a couple of values. Doesn't need much more than a sanity check but better to do the sanity check now rather than at the interop event.

**Comment by CarlBeek** [comment]
Apologies, this slipped my radar! Test vectors for privkeys are on their way ASAP.

If you read this issue from the beginning, there are two concurrent proposals (@djrtwo's and mine) and neither seem to have been chosen as the final one. I would like to propose a final variant becuase @djrtwo's has a ~10% chance of choosing a privkey that is greater than the curve order and mine in not constant time.

*Note again, this new deterministic privkey algorithm is not secure (due to severe modulo bias) and should only be used for testing purposes.*

```python
CURVE_ORDER = 52435875175126190479447740508185965837690552500527637822603658699938581184513
validator_index_to_pubkey = {}
pubkey_to_privkey = {}
privkey_to_pubkey = {}
for index in range(N):
    privkey = int.from_bytes(
        sha256(int_to_bytes(n=index, length=32)),
        byteorder='little'
    ) % CURVE_ORDER
    pubkey = bls.privtopubkey(privkey)
    pubkey_to_privkey[pubkey] = privkey
    privkey_to_pubkey[privkey] = pubkey
    validator_index_to_pubkey[index] = pubkey
```

**Comment by ajsutton** [comment]
Thanks @CarlBeek that's extremely helpful.  I've now code to do the required generation setup for Artemis and just need to actually hook it into the config/startup.  Getting similar test vectors for the generated deposits and final `BeaconState` would be perfect.  I'm happy to share the data my code generates if that's useful, but I've been working in Eth2 for all of about a week so don't have a lot of confidence I've got it right. :)

Also, any chance we could update the description in the issue to reflect this final version of the private key generation and the link to test vectors?  That will save others from having to read the entire comment thread.

**Comment by djrtwo** [comment]
@CarlBeek @ajsutton Added Carl's modified version to the description of the issue

**Comment by djrtwo** [comment]
this has been addressed as a interop standard merged into the repo. See #71
