### ISSUE TITLE
Interop arbitrary state start

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-pm#75]
### Problem

The interop spec states that clients must ["start chain from specified state"](https://github.com/ethereum/eth2.0-pm/tree/master/interop/mocked_start#start-chain-from-specified-state), which can be "some arbitrary state at any point in a chain's history".

I think this requirement is too broad. Lighthouse currently makes the assumption that it has all blocks/states up to the most recent finalized state. I would expect such assumptions to be common. It's also not clear how fork choice should behave without access to prior justified states.

The current scope also includes states that might be half-way through an epoch. Shuffling caches might make assumptions that if we're processing some block `n > 1` deep into some epoch then we've already cached the shuffling.

I don't doubt that we _could_ implement the ability to start from any arbitrary state, however I think it's a little premature and there would be quite a lot of edge-cases.

### Suggestions

I think we we should reduce the scope of starting states to something like: _the state from the first slot of a finalized epoch_. I'm not even sure that's accurate.

I don't think it's worth us trying to define this scenario right now and my preference would be to say it's not a required for the Canada interop.

**Comment by ajsutton** [comment]
I'd agree with this. If we can solve all the interoperability problems found just with clients starting from genesis in a week we'd be doing exceptionally well.  And specific corner cases that are hard to reproduce in a chain starting from genesis are probably worth writing automated reference tests to cover anyway.

**Comment by mkalinin** [comment]
> I don't think it's worth us trying to define this scenario right now and my preference would be to say it's not a required for the Canada interop.

I agree with this.

> I think we we should reduce the scope of starting states to something like: _the state from the first slot of a finalized epoch_. I'm not even sure that's accurate.

I'd make it a bit more generic. We can start from a state computed by epoch transition with arbitrary epoch number. In that case this state should be considered in the same way as if it would be a _finalized state_ on a boundary of weak subjectivity period. From a regular node standpoint it should be OK if there is no chain data behind weak subjectivity period.

**Comment by djrtwo** [comment]
> I don't think it's worth us trying to define this scenario right now and my preference would be to say it's not a required for the Canada interop.

agreed. We can discuss in person this requirement and how it fits more generally in with the requirement of a node being able to start from a finalized state.

> We can start from a state computed by epoch transition with arbitrary epoch number. 

I think this is correct. No need to start in the middle of an epoch. Similar to starting from a finalized state when joining the network, essentially by specifying state `S` start state, it is essentially your genesis and should be treated as both latest finalized and justified wrt local fork choice.
